"""Compile context packs for future agent dispatch."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def compile_context_markdown(state: dict[str, Any]) -> str:
    task = state.get("task_data", {})
    skills = state.get("required_skills", [])
    mcps = state.get("required_mcps", [])
    handoffs = state.get("recent_handoffs", [])
    events = state.get("recent_events", [])
    files = state.get("files_to_inspect", [])

    handoff_section = "\n".join(
        f"- [[{h.get('name', '')}]] — `{h.get('path', '')}`" for h in handoffs
    ) or "- (none)"

    event_section = "\n".join(
        f"- `{e.get('ts', '—')}` {e.get('agent', '—')} — {e.get('type') or e.get('event', 'note')}: {e.get('detail', '')}"
        for e in events
    ) or "- (none)"

    constraints = task.get("constraints", [])
    if isinstance(constraints, str):
        constraints = [constraints]
    acceptance = task.get("acceptance", task.get("acceptance_criteria", []))
    if isinstance(acceptance, str):
        acceptance = [acceptance]

    return f"""# Context Pack: {state.get('task_id', '')}

## Task Summary
- **Title:** {state.get('title', '')}
- **Status:** {state.get('status', '')}
- **Owner:** {state.get('owner', '')}
- **Risk:** {state.get('risk_level', '')}

## Objective
{state.get('objective', '')}

## Constraints
{chr(10).join(f'- {c}' for c in constraints) if constraints else '- (none)'}

## Acceptance Criteria
{chr(10).join(f'- {a}' for a in acceptance) if acceptance else '- (none)'}

## Suggested Team
- **Team:** [[{state.get('selected_team', '')}]] (score {state.get('selected_team_score', 0)})
- **Primary agent:** {state.get('recommended_primary_agent', '—')}
- **Reviewer:** {state.get('recommended_reviewer', '—')}

## Suggested Agents
{', '.join(state.get('selected_agents', [])) or '—'}

## Relevant Skills
{chr(10).join(f'- [[{s}]]' for s in skills) or '- (none)'}

## Relevant MCPs
{chr(10).join(f'- [[{m}]]' for m in mcps) or '- (none)'}

## Recent Handoffs
{handoff_section}

## Recent Events
{event_section}

## Files To Inspect
{chr(10).join(f'- `{f}`' for f in files) or '- (none)'}

## Recommended Prompt For Agent
{state.get('recommended_prompt', '')}

---
*Generated by Agentic OS orchestrator. Planning only — not executed automatically.*
"""


def compile_context_json(state: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": state.get("task_id"),
        "run_id": state.get("run_id"),
        "title": state.get("title"),
        "objective": state.get("objective"),
        "required_skills": state.get("required_skills", []),
        "selected_team": state.get("selected_team"),
        "selected_agents": state.get("selected_agents", []),
        "required_mcps": state.get("required_mcps", []),
        "approval_required": state.get("approval_required"),
        "approval_level": state.get("approval_level"),
        "files_to_inspect": state.get("files_to_inspect", []),
        "recommended_prompt": state.get("recommended_prompt"),
    }


def write_context_pack(run_dir: Path, state: dict[str, Any], dry_run: bool) -> tuple[str, str]:
    md = compile_context_markdown(state)
    js = compile_context_json(state)
    md_path = run_dir / "context_pack.md"
    json_path = run_dir / "context_pack.json"
    if not dry_run:
        run_dir.mkdir(parents=True, exist_ok=True)
        md_path.write_text(md, encoding="utf-8")
        json_path.write_text(json.dumps(js, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(md_path), str(json_path)